jobs:
- pysparkJob:
    mainPythonFileUri: gs://dataproc-temp-yt-123456/src/simple_spark_job1.py
  stepId: simple-pyspark1
- pysparkJob:
    mainPythonFileUri: gs://dataproc-temp-yt-123456/src/simple_spark_job2.py
  stepId: simple-pyspark2
labels:
  project: demo-dataproc
placement:
  managedCluster:
    clusterName: demo-three-node-cluster-1234
    config:
      gceClusterConfig:
        zoneUri: europe-west1-b
      masterConfig:
        diskConfig:
          bootDiskSizeGb: 500
        machineTypeUri: n1-standard-4
      softwareConfig:
        imageVersion: 1.3-deb9
      workerConfig:
        diskConfig:
          bootDiskSizeGb: 500
        machineTypeUri: n1-standard-4
        numInstances: 2